/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalesTerminosRouteImport } from './routes/legales.terminos'
import { Route as LegalesPrivacidadRouteImport } from './routes/legales.privacidad'
import { Route as LegalesComisionesRouteImport } from './routes/legales.comisiones'
import { Route as LegalesArrepentimientoRouteImport } from './routes/legales.arrepentimiento'
import { Route as AdminReporteriaRouteImport } from './routes/admin.reporteria'
import { Route as AdminRecaudacionRouteImport } from './routes/admin.recaudacion'
import { Route as AdminMovimientosRouteImport } from './routes/admin.movimientos'
import { Route as AdminMonitoreoRouteImport } from './routes/admin.monitoreo'
import { Route as AdminKycRouteImport } from './routes/admin.kyc'
import { Route as AdminConsorcioRouteImport } from './routes/admin.consorcio'
import { Route as AdminConfigRouteImport } from './routes/admin.config'
import { Route as AdminComplianceRouteImport } from './routes/admin.compliance'
import { Route as AdminComisionesRouteImport } from './routes/admin.comisiones'
import { Route as AdminClientesRouteImport } from './routes/admin.clientes'
import { Route as AdminCbuRouteImport } from './routes/admin.cbu'
import { Route as AdminAlquileresRouteImport } from './routes/admin.alquileres'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LegalesTerminosRoute = LegalesTerminosRouteImport.update({
  id: '/legales/terminos',
  path: '/legales/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesPrivacidadRoute = LegalesPrivacidadRouteImport.update({
  id: '/legales/privacidad',
  path: '/legales/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesComisionesRoute = LegalesComisionesRouteImport.update({
  id: '/legales/comisiones',
  path: '/legales/comisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalesArrepentimientoRoute = LegalesArrepentimientoRouteImport.update({
  id: '/legales/arrepentimiento',
  path: '/legales/arrepentimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReporteriaRoute = AdminReporteriaRouteImport.update({
  id: '/reporteria',
  path: '/reporteria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecaudacionRoute = AdminRecaudacionRouteImport.update({
  id: '/recaudacion',
  path: '/recaudacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMovimientosRoute = AdminMovimientosRouteImport.update({
  id: '/movimientos',
  path: '/movimientos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMonitoreoRoute = AdminMonitoreoRouteImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConsorcioRoute = AdminConsorcioRouteImport.update({
  id: '/consorcio',
  path: '/consorcio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRoute = AdminConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComplianceRoute = AdminComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminComisionesRoute = AdminComisionesRouteImport.update({
  id: '/comisiones',
  path: '/comisiones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientesRoute = AdminClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCbuRoute = AdminCbuRouteImport.update({
  id: '/cbu',
  path: '/cbu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlquileresRoute = AdminAlquileresRouteImport.update({
  id: '/alquileres',
  path: '/alquileres',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/alquileres': typeof AdminAlquileresRoute
  '/admin/cbu': typeof AdminCbuRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comisiones': typeof AdminComisionesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/consorcio': typeof AdminConsorcioRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/monitoreo': typeof AdminMonitoreoRoute
  '/admin/movimientos': typeof AdminMovimientosRoute
  '/admin/recaudacion': typeof AdminRecaudacionRoute
  '/admin/reporteria': typeof AdminReporteriaRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/alquileres': typeof AdminAlquileresRoute
  '/admin/cbu': typeof AdminCbuRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comisiones': typeof AdminComisionesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/consorcio': typeof AdminConsorcioRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/monitoreo': typeof AdminMonitoreoRoute
  '/admin/movimientos': typeof AdminMovimientosRoute
  '/admin/recaudacion': typeof AdminRecaudacionRoute
  '/admin/reporteria': typeof AdminReporteriaRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/alquileres': typeof AdminAlquileresRoute
  '/admin/cbu': typeof AdminCbuRoute
  '/admin/clientes': typeof AdminClientesRoute
  '/admin/comisiones': typeof AdminComisionesRoute
  '/admin/compliance': typeof AdminComplianceRoute
  '/admin/config': typeof AdminConfigRoute
  '/admin/consorcio': typeof AdminConsorcioRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/monitoreo': typeof AdminMonitoreoRoute
  '/admin/movimientos': typeof AdminMovimientosRoute
  '/admin/recaudacion': typeof AdminRecaudacionRoute
  '/admin/reporteria': typeof AdminReporteriaRoute
  '/legales/arrepentimiento': typeof LegalesArrepentimientoRoute
  '/legales/comisiones': typeof LegalesComisionesRoute
  '/legales/privacidad': typeof LegalesPrivacidadRoute
  '/legales/terminos': typeof LegalesTerminosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/alquileres'
    | '/admin/cbu'
    | '/admin/clientes'
    | '/admin/comisiones'
    | '/admin/compliance'
    | '/admin/config'
    | '/admin/consorcio'
    | '/admin/kyc'
    | '/admin/monitoreo'
    | '/admin/movimientos'
    | '/admin/recaudacion'
    | '/admin/reporteria'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/alquileres'
    | '/admin/cbu'
    | '/admin/clientes'
    | '/admin/comisiones'
    | '/admin/compliance'
    | '/admin/config'
    | '/admin/consorcio'
    | '/admin/kyc'
    | '/admin/monitoreo'
    | '/admin/movimientos'
    | '/admin/recaudacion'
    | '/admin/reporteria'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/alquileres'
    | '/admin/cbu'
    | '/admin/clientes'
    | '/admin/comisiones'
    | '/admin/compliance'
    | '/admin/config'
    | '/admin/consorcio'
    | '/admin/kyc'
    | '/admin/monitoreo'
    | '/admin/movimientos'
    | '/admin/recaudacion'
    | '/admin/reporteria'
    | '/legales/arrepentimiento'
    | '/legales/comisiones'
    | '/legales/privacidad'
    | '/legales/terminos'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LegalesArrepentimientoRoute: typeof LegalesArrepentimientoRoute
  LegalesComisionesRoute: typeof LegalesComisionesRoute
  LegalesPrivacidadRoute: typeof LegalesPrivacidadRoute
  LegalesTerminosRoute: typeof LegalesTerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/legales/terminos': {
      id: '/legales/terminos'
      path: '/legales/terminos'
      fullPath: '/legales/terminos'
      preLoaderRoute: typeof LegalesTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/privacidad': {
      id: '/legales/privacidad'
      path: '/legales/privacidad'
      fullPath: '/legales/privacidad'
      preLoaderRoute: typeof LegalesPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/comisiones': {
      id: '/legales/comisiones'
      path: '/legales/comisiones'
      fullPath: '/legales/comisiones'
      preLoaderRoute: typeof LegalesComisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legales/arrepentimiento': {
      id: '/legales/arrepentimiento'
      path: '/legales/arrepentimiento'
      fullPath: '/legales/arrepentimiento'
      preLoaderRoute: typeof LegalesArrepentimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reporteria': {
      id: '/admin/reporteria'
      path: '/reporteria'
      fullPath: '/admin/reporteria'
      preLoaderRoute: typeof AdminReporteriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recaudacion': {
      id: '/admin/recaudacion'
      path: '/recaudacion'
      fullPath: '/admin/recaudacion'
      preLoaderRoute: typeof AdminRecaudacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/movimientos': {
      id: '/admin/movimientos'
      path: '/movimientos'
      fullPath: '/admin/movimientos'
      preLoaderRoute: typeof AdminMovimientosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/monitoreo': {
      id: '/admin/monitoreo'
      path: '/monitoreo'
      fullPath: '/admin/monitoreo'
      preLoaderRoute: typeof AdminMonitoreoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/consorcio': {
      id: '/admin/consorcio'
      path: '/consorcio'
      fullPath: '/admin/consorcio'
      preLoaderRoute: typeof AdminConsorcioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config': {
      id: '/admin/config'
      path: '/config'
      fullPath: '/admin/config'
      preLoaderRoute: typeof AdminConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/compliance': {
      id: '/admin/compliance'
      path: '/compliance'
      fullPath: '/admin/compliance'
      preLoaderRoute: typeof AdminComplianceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comisiones': {
      id: '/admin/comisiones'
      path: '/comisiones'
      fullPath: '/admin/comisiones'
      preLoaderRoute: typeof AdminComisionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clientes': {
      id: '/admin/clientes'
      path: '/clientes'
      fullPath: '/admin/clientes'
      preLoaderRoute: typeof AdminClientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cbu': {
      id: '/admin/cbu'
      path: '/cbu'
      fullPath: '/admin/cbu'
      preLoaderRoute: typeof AdminCbuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alquileres': {
      id: '/admin/alquileres'
      path: '/alquileres'
      fullPath: '/admin/alquileres'
      preLoaderRoute: typeof AdminAlquileresRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlquileresRoute: typeof AdminAlquileresRoute
  AdminCbuRoute: typeof AdminCbuRoute
  AdminClientesRoute: typeof AdminClientesRoute
  AdminComisionesRoute: typeof AdminComisionesRoute
  AdminComplianceRoute: typeof AdminComplianceRoute
  AdminConfigRoute: typeof AdminConfigRoute
  AdminConsorcioRoute: typeof AdminConsorcioRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminMonitoreoRoute: typeof AdminMonitoreoRoute
  AdminMovimientosRoute: typeof AdminMovimientosRoute
  AdminRecaudacionRoute: typeof AdminRecaudacionRoute
  AdminReporteriaRoute: typeof AdminReporteriaRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlquileresRoute: AdminAlquileresRoute,
  AdminCbuRoute: AdminCbuRoute,
  AdminClientesRoute: AdminClientesRoute,
  AdminComisionesRoute: AdminComisionesRoute,
  AdminComplianceRoute: AdminComplianceRoute,
  AdminConfigRoute: AdminConfigRoute,
  AdminConsorcioRoute: AdminConsorcioRoute,
  AdminKycRoute: AdminKycRoute,
  AdminMonitoreoRoute: AdminMonitoreoRoute,
  AdminMovimientosRoute: AdminMovimientosRoute,
  AdminRecaudacionRoute: AdminRecaudacionRoute,
  AdminReporteriaRoute: AdminReporteriaRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LegalesArrepentimientoRoute: LegalesArrepentimientoRoute,
  LegalesComisionesRoute: LegalesComisionesRoute,
  LegalesPrivacidadRoute: LegalesPrivacidadRoute,
  LegalesTerminosRoute: LegalesTerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
